Comprobación del test

diff --git a/buildspec.yml b/buildspec.yml
--- a/buildspec.yml
+++ b/buildspec.yml
@@ -1,9 +1,25 @@
 version: 0.2
+
 phases:
   build:
     commands:
-      - echo "Running updateSongInfo function"
+      - echo "Running build phase"
       - cat index.html
+
+  post_build:
+    commands:
+      - echo "Running test phase"
+      - if grep -q "<script src=\"script.js\"></script>" index.html; then
+          echo "script.js is correctly referenced in index.html";
+        else
+          echo "Error: script.js is not correctly referenced in index.html" && exit 1;
+        fi
+      - if grep -q "<link rel=\"stylesheet\" href=\"style.css\">" index.html; then
+          echo "style.css is correctly referenced in index.html";
+        else
+          echo "Error: style.css is not correctly referenced in index.html" && exit 1;
+        fi
+
 artifacts:
   files:
     - index.html
